### ISSUE TITLE
data corruption with acd_cli

### ISSUE THREAD

**Issue by jxer** [rfjakob/gocryptfs#59]
i know nothing about this stuff, another poster wrote this over on acd_cli is there any truth to it?

"if you're mounting both acd and gocrtpyfs over fuse, what options are you using when you initialized gocryptfs? I ran into data corruption issues before doing that based on how it was caching the results of read calls through acdcli's fuse."

**Comment by rfjakob** [comment]
Sorry, I have never used acdcli, so I can't comment on that. The good news is that data corruption will be detected by the checksums that gocryptfs adds to the data. If it sees a corrupted block it will log a message to syslog. So I'd recommend running `journalctl -f` and then try to access the files, this will give you a pretty good idea of what is going on.

**Comment by jxer** [comment]
@bgemmill,

can you provide some form of info for rfjakob,

@rfjakob does his comment make sense to you? can having 2 fuse mounts have this issue?

i really would like this answer before spending 4 days uploading just to find out its all corrupted

**Comment by jxer** [comment]
yea this isn't really working for me, i need to do acdcli sync's before it can even see the files copied, it shows the directory's but the file size is 0, a sync is required before it shows up, not sure this really helps me over encfs

**Comment by bgemmill** [comment]
@rfjakob I ran into issues with gocryptfs when I was mounting it over acdcli's mount.

When I'd copy an unencrypted file into gocryptfs's upper mount, it would start interacting with acdcli in a way that would corrupt files:

1) gocryptfs would first try to read the first N bytes of the file.
2) since that file doesn't exist on acdcli yet, acdcli would return no bytes read
3) either fuse or gocryptfs would somehow cache that result, since the final file would contain all 0s for those first N bytes.

Does gocryptfs mmap in the first N bytes to keep (re)computing the crypto checksum of a file there, or does it use that initial read like a truncate to make the file have some initial size?

Without looking at the gocryptfs code, those are my best guesses as to what might trigger that interaction.

**Comment by rfjakob** [comment]
Ok, I reproduced this, with with the ciphertext directory of gocryptfs inside an acdcli mount.

My canonical sanity check, extracting [linux-3.0.tar.gz](https://cdn.kernel.org/pub/linux/kernel/v3.0/linux-3.0.tar.gz) gives me lots of these:

```
$ tar xf /tmp/linux-3.0.tar.gz 
tar: linux-3.0/.gitignore: Cannot open: Function not implemented
tar: linux-3.0/.mailmap: Cannot open: Function not implemented
tar: linux-3.0/COPYING: Cannot open: Function not implemented
[...]
```

In syslog I see this:

```
Nov 06 13:34:33 brikett gocryptfs[16228]: ReadDirIVAt: Read failed: EOF
Nov 06 13:34:33 brikett gocryptfs[16228]: go-fuse: can't convert error type: EOF
[...]
```

Now, let's try something simpler, directly in the acdcli mount, without gocryptfs involved.
We write `12345678` to a file called `file` and `cat` it immediately, then again after one second:

```
$ echo 12345678 > file && echo "first read:" && cat file && sleep 1 && echo "second read:" && cat file
first read:
second read:
12345678
```

The first `cat` comes back empty, even though we have just written into it. This is a bug in acdcli. Don't use gocryptfs on acdcli until this is fixed!

**Comment by jxer** [comment]
@yadayada

any comments on this?

**Comment by bgemmill** [comment]
@rfjakob can you give my PR a shot?
https://github.com/yadayada/acd_cli/pull/374
Note that you'll need to delete your nodes.db and sync again when you switch to this branch.

When using it I see your test work correctly:
$ echo 12345678 > file && echo "first read:" && cat file && sleep 1 && echo "second read:" && cat file
first read:
12345678
second read:
12345678

It also looks like the issue I was seeing was fixed somewhere between gocryptfs v1 and the current v1.1.1. So if things look good on your end the issue I saw before may just be gone now.
For reference, I was testing with:
dd if=/dev/urandom of=file.blob bs=1MB count 100
cp file.blob /mnt/gocryptfs/
cp /mnt/gocryptfs/file.blob file.blob2
vimdiff file.blob file.blob2

**Comment by rfjakob** [comment]
@bgemmill Yes, this looks better! I managed create a few directories without hitting errors.
Extracting the linux tarball will probably take hours, though. Creating a file takes about 0.7 seconds:

```
$ time (for i in `seq 1 10`; do echo $i ; echo -n > $i; done)
1
2
3
4
5
6
7
8
9
10

real 0m7.959s
user 0m0.001s
sys  0m0.004s
```

**Comment by rfjakob** [comment]
Answering the other questions for gocryptfs: The header of each file is fixed. It is created when the file is first written to. It is not updated by later writes and read only once for each `open()`. gocryptfs does not use mmap.

**Comment by bgemmill** [comment]
If @rfjakob is out closing tickets, I have not observed this issue in the last 500G I've moved to amazon and back with the mentioned PR.

**Comment by rfjakob** [comment]
@bgemmill that's good to hear!

Do you know how the situation is with mainline ACD? It might make sense to keep this ticket open until https://github.com/yadayada/acd_cli/pull/374 is merged, as a warning to ACD users.

**Comment by bgemmill** [comment]
Last I checked, mainline still showed bad behavior for the example you mentioned:
`$ echo 12345678 > file && echo "first read:" && cat file && sleep 1 && echo "second read:" && cat file`

I'd definitely steer gocryptfs users to the PR or hold off until it's merged.

**Comment by rfjakob** [comment]
It's been a few months of having the reminder here, hopefully people have noticed, but there isn't more I can do from the gocryptfs side. Closing the ticket.

**Comment by bgemmill** [comment]
Since Amazon shut down acdcli, there's not much to be done on the far end either. Thanks for helping to debug this anyway @rfjakob!
